import React, { createContext } from 'react';

const CurrentGameContext = createContext({
    loginWhite: '',
    setLoginWhite: () => {},
    loginBlack: '',
    setLoginBlack: () => {},
    newGame: '',
    setNewGame: () => {},
    playerOneData: "",
    setPlayerOneData: () => {},
    playerTwoData: "",
    setPlayerTwoData: () => {},
    playerOne: "",
    setPlayerOne: () => {},
    playerTwo: "",
    setPlayerTwo: () => {},
    updated: "",
    setUpdated: () => {},
    activePlayer: "",
    setActivePlayer: () => {},
    selection: "",
    setSelection: () => {},
    pieces: [],
    setPieces: () => {},
    locations: [],
    setLocations: () => {},
    underAttack: [],
    setUnderAttack: () => {},
    taken: [],
    setTaken: () => {},
    castled: [],
    setCastled: () => {},
    inCheck: [],
    setInCheck: () => {},
    assassinAttempts: [],
    setAssassinAttempts: () => {},
    moving: "",
    setMoving: () => {},
    gameEnd: '',
    setGameEnd: () => {},
    pinned: [],
    setPinned: () => {},
    doubleStepped: [],
    setDoubleStepped: () => {}
})

export default CurrentGameContext
